### ISSUE TITLE
is this for neo4j community edition ?

### ISSUE THREAD

**Issue by osman-mohamad** [simkoc/neo4j-manager#1]
And it solve it by create new config file and reactivate the neo4j instance with the new configucration ?

can this package used to manage multiple running dbs instances at the same time ?

thank you

**Comment by simkoc** [comment]
The only thing this program really does is basically manage the folder in the `/data/databases/` folder of your neo4j instance. Consequently, you can only have one active but changing between multiple distinct databases is easier using this python script.

**Comment by osman-mohamad** [comment]
thank you @simkoc

**Comment by osman-mohamad** [comment]
is there any way to manage multiple neo4j dbs in the same server in the same time with the community edition ?

**Comment by simkoc** [comment]
@osman-mohamad  not that I am aware of. I am not even sure the enterprise version can do that.
